import React, { useRef, useState } from 'react';
import Sidebar from '../components/Sidebar';
import { useNavigate } from 'react-router-dom';
import { useLocation } from 'react-router-dom';


interface Guide {
    _id: string;
    title: string;
    content: string;
    category: string;
    updatedAt: string;
}

// Mapping of guide categories to image file names
const imageMap: { [key: string]: string } = {
    floods: 'floods.jpg',
    earthquakes: 'earthquake.jpg',
    wildfires: 'wildfire2.jpg',
    tornadoes: 'tornado.jpg',
    winters: 'winter.jpg',
    other: 'other.jpg'
}; 
const Other: React.FC = () => {
    const [darkMode, setDarkMode] = useState(false);
    const [showTooltip, setShowTooltip] = useState(false);
    const location = useLocation();
    const { guide } = location.state as { guide: Guide }; // Casting the state to the Guide type

    // Function to toggle dark mode
    const toggleDarkMode = () => {
        setDarkMode(!darkMode);
    };

    // Styles for dark mode
    const darkModeStyles = {
        backgroundColor: 'black',
        color: 'white'
    };

    // Apply dark mode styles if darkMode is true, otherwise use empty object
    const currentStyles = darkMode ? darkModeStyles : {};
    const navigate = useNavigate();
    const handleGoBack = () => {
        navigate('/guidePreview');
    };
    const imageName = imageMap[guide.category];
    const imageUrl = `${process.env.PUBLIC_URL}/${imageName}`;
  return (
    <div className="flex h-full">
            <Sidebar />
            <div style={{ maxHeight: 'calc(100vh - 100px)', overflowY: 'auto' }}>
                <div style={{ maxWidth: '100%', overflowY: 'auto' }}>
                    <div className="w-full h-72 bg-cover bg-center" style={{ backgroundImage: `url(${imageUrl})` }}></div>
                    <div className="flex justify-center items-center space-x-4 my-4">
                        <button
                                onClick={toggleDarkMode}
                                onMouseEnter={() => setShowTooltip(true)}
                                onMouseLeave={() => setShowTooltip(false)}
                                className="flex justify-center items-center space-x-4 my-4 px-4 py-2 bg-blue-500 text-white rounded-md focus:outline-none focus:ring"
                            >
                                {darkMode ? 'Light Mode' : 'Dark Mode'}
                            </button>

                            {/* Tooltip */}
                            {showTooltip && (
                                <div className="absolute top-60 left-100 bg-cyan-600 text-white p-3 rounded-full shadow hover:bg-cyan-700 transition duration-300">
                                    <span className="text-sm">
                                        Every website has a carbon footprint but by choosing to view ours in dark mode, you can reduce the screen power and carbon emissions generated by your visit. Try it here.
                                    </span>
                                </div>
                            )}
                        </div>
                        </div>
                <div className="ml-4 content-section mb-6" style={{ fontFamily: 'Brygada, serif', ...currentStyles }}>
                    <p className="mb-4 text-lg">
                    Recovering from a disaster is usually a gradual process. Safety is a primary issue, as are mental and physical well-being. If assistance is available, knowing how to access it makes the process faster and less stressful. This section offers some general advice on steps to take after disaster strikes in order to begin getting your home, your community and your life back to normal.
                    </p>
                    <h1 className="ml-4 text-2xl font-bold text my-4"><b><u>First, if you have damages following a disaster, contact your local emergency manager.</u></b></h1>
                    <ul className="list-disc pl-5 space-y-2">
                        <li className="text-lg">Last a few hours or several days.</li>
                        <li className="text-lg">Cut off heat, power, and communication services.</li>
                        <li className="text-lg">Put older adults, children, sick individuals, and pets at greater risk.</li>
                    </ul>
                    <h1 className="ml-4 text-2xl font-bold text my-4"><b><u>If you have insurance, contact your insurance agent to file a claim.</u></b></h1>
                    <ul className="list-disc pl-5 space-y-2">
                        <li className="text-lg">Make sure to document all your damages – before you clean up, take photos and make a list.</li>
                        <li className="text-lg">Save all your receipts for post-damage repair and clean up.</li>
                        <li className="text-lg">If you have insurance and damages, you must file a claim with your insurance company.</li>
                    </ul>
                    <h1 className="ml-4 text-2xl font-bold text my-4"><b><u>Recovering from a disaster is a gradual process, take care of yourself and your family</u></b></h1>
                    <ul className="list-disc pl-5 space-y-2">
                        <li className="text-lg">Your first concern after a disaster is your family's health and safety. You need to consider possible safety issues and monitor family health and well-being.</li>
                        <li className="text-lg">If you are returning home following a disaster, know it can be both physically and mentally challenging. Above all, use caution. You may be anxious to see your property, but do not return home before local officials say it is safe to return.</li>
                        <li className="text-lg">Administer first aid and seek medical attention for any injured person following a disaster.</li>
                        <li className="text-lg">Check for injuries. Do not attempt to move seriously injured persons unless they are in immediate danger of death or further injury. If you must move an unconscious person, first stabilize the neck and back, then call for help immediately.</li>
                    </ul>
                    <h1 className="ml-4 text-2xl font-bold text my-4"><b><u>Safety Issues</u></b></h1>
                    <ul className="list-disc pl-5 space-y-2">
                        <li className="text-lg">Be aware of new safety issues created by the disaster. Watch for washed out roads, contaminated buildings, contaminated water, gas leaks, broken glass, damaged electrical wiring and slippery floors.</li>
                        <li className="text-lg">Walk carefully around the outside and check for loose power lines, gas leaks and structural damage. If you have any doubts about safety, have your residence inspected by a qualified building inspector or structural engineer before entering.</li>
                        <li className="ml-4 text-lg flex items-center">
                            <span>Do not enter your damaged home if:</span>
                        </li>
                        <li className="ml-20 text-lg flex items-center">
                        You smell gas.
                        </li>
                        <li className="ml-20 text-lg flex items-center">
                        loodwaters remain around the building.
                        </li>
                        <li className="ml-20 text-lg flex items-center">
                        Authorities have not declared it safe to enter.
                        </li>
                        <li className="text-lg">Inform local authorities about health and safety issues, including chemical spills, downed power lines, washed out roads, smoldering insulation and dead animals.</li>
                        <li className="text-lg">Keep a battery-powered radio with you for emergency updates from local officials.</li>
                    </ul>

                </div>
                <button
                    onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
                    className="fixed bottom-10 right-10 bg-cyan-600 text-white p-3 rounded-full shadow hover:bg-cyan-700 transition duration-300"
                >
                    Return to Top
                </button>
                <button
                    onClick={handleGoBack}
                    className="fixed bottom-10 left-100 bg-cyan-600 text-white p-3 rounded-full shadow hover:bg-cyan-700 transition duration-300"
                >
                    Back to preview
                </button>
            </div>
        </div>
  )
}

export default Other